openapi: 3.0.1
info:
  title: lab
  version: '1.0'
  description: 研究室配属調査API
  contact: {}
servers:
  - url: 'http://lab-backend:8080'
paths:
  '/graduate/{userId}/save':
    parameters:
      - $ref: '#/components/parameters/userId'
    post:
      summary: 進学情報の保存
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/OK'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      operationId: postGraduateSave
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/graduate'
      description: 進学情報を保存する
      security:
        - bearer: []
  '/graduate/{userId}/fix':
    parameters:
      - $ref: '#/components/parameters/userId'
    patch:
      summary: 進学情報の修正
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/OK'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      operationId: postGraduateFix
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/graduate'
      description: 進学情報を修正する
      security:
        - bearer: []
components:
  schemas:
    graduate:
      title: graduate
      type: boolean
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int64
          description: Error code
        message:
          type: string
          description: Error message
  responses:
    OK:
      description: Success
      content:
        application/json:
          schema: {}
      headers:
        Set-Cookie:
          schema:
            type: string
            example: fksd-43jfegljer-dlksjflkasn
          description: jwtの情報
  securitySchemes:
    bearer:
      type: http
      scheme: basic
  parameters:
    userId:
      name: userId
      in: path
      required: true
      schema:
        type: string
        example: '1316190124'
      description: 学籍番号