openapi: 3.0.1
info:
  title: lab
  version: '1.0'
  description: 研究室配属調査API
  contact: {}
servers:
  - url: 'http://lab-backend:8080'
paths:
  /login:
    post:
      summary: ログイン
      tags: []
      operationId: login
      description: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
        description: ''
      responses:
        '200':
          $ref: '#/components/responses/OK'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
  /logout:
    get:
      summary: ログアウト
      tags: []
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
      operationId: logout
      parameters:
        - $ref: '#/components/parameters/Set-Cookie'
      description: ログアウトする
  '/graduate/{userId}/save':
    parameters:
      - $ref: '#/components/parameters/userId'
    post:
      summary: 進学情報の保存
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/OK'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
      operationId: postGraduateSave
      parameters:
        - $ref: '#/components/parameters/Set-Cookie'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/graduate'
      description: 進学情報を保存する
      security:
        - bearer: []
  '/graduate/{userId}/fix':
    parameters:
      - $ref: '#/components/parameters/userId'
    patch:
      summary: 進学情報の修正
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/OK'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
      operationId: postGraduateFix
      parameters:
        - $ref: '#/components/parameters/Set-Cookie'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/graduate'
      description: 進学情報を修正する
      security:
        - bearer: []
  '/lab/{userId}/save':
    parameters:
      - $ref: '#/components/parameters/userId'
    post:
      summary: 研究室調査結果の保存
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/OK'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
      operationId: postLabSave
      parameters:
        - $ref: '#/components/parameters/Set-Cookie'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/labs'
      description: 配属情報を保存する
      security:
        - bearer: []
  '/lab/{userId}/fix':
    parameters:
      - $ref: '#/components/parameters/userId'
    patch:
      summary: 研究室調査結果の修正
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/OK'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
      operationId: postLabFix
      parameters:
        - $ref: '#/components/parameters/Set-Cookie'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/labs'
      description: 配属情報を修正する
      security:
        - bearer: []
  /home:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/home'
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      operationId: getHome
      description: 回答情報を取得する
      parameters:
        - $ref: '#/components/parameters/Set-Cookie'
      security:
        - bearer: []
components:
  schemas:
    labs:
      title: lab
      type: object
      properties:
        name:
          type: string
        professors:
          type: array
          items:
            $ref: '#/components/schemas/professor'
      required:
        - name
        - professors
    professor:
      title: professor
      type: object
      properties:
        name:
          type: string
        point:
          type: integer
          format: int64
      required:
        - name
        - point
    graduate:
      title: graduate
      type: boolean
    user:
      title: user
      type: object
      description: ログイン情報
      properties:
        user_id:
          type: string
          example: '1316190124'
        password:
          type: string
          example: password
      required:
        - user_id
        - password
    home:
      title: home
      type: object
      x-examples: {}
      properties:
        user_id:
          type: string
        graduate:
          $ref: '#/components/schemas/graduate'
        labs:
          type: array
          items:
            $ref: '#/components/schemas/labs'
      required:
        - user_id
        - graduate
        - labs
  responses:
    OK:
      description: Success
      content:
        application/json:
          schema: {}
      headers:
        Set-Cookie:
          schema:
            type: string
            example: fksd-43jfegljer-dlksjflkasn
          description: jwtの情報
  securitySchemes:
    bearer:
      type: http
      scheme: basic
  parameters:
    Set-Cookie:
      name: Set-Cookie
      in: header
      required: false
      schema:
        type: string
        example: JSESSIONID=abcde12345; Path=/; HttpOnly
      description: jwtの情報を入れる
    userId:
      name: userId
      in: path
      required: true
      schema:
        type: string
        example: '1316190124'
      description: 学籍番号
